### ISSUE TITLE
[bug] schema recompiled error message said there was another user when I'm the only one

### ISSUE THREAD

**Issue by whatSocks** [structr/structr#499]
<img width="626" alt="screenshot 2017-05-15 17 13 45" src="https://cloud.githubusercontent.com/assets/2731744/26079765/e5602bbc-3991-11e7-8217-0dc9720c0335.png">

Steps

* be only user working on a structr app
* recompile schema
* see error message referencing another user
* be confused since i'm the only user!

**Comment by vigorouscoding** [comment]
Which actions exactly did you take? This message is pretty new and supposed to be ignored by the app if you yourself did the change. It looks like there is (at least) one schema change where this dialog is not suppressed

**Comment by vigorouscoding** [comment]
I found one way to reproduce this: If you make changes to the schema before the previous change has been saved (i.e. the schema has been recompiled) this will trigger the message.
I will make a change so that this is prevented - if you find any other ways to reproduce this message (after the update) please share them so I can fix it!

Thanks for reporting this!

**Comment by vigorouscoding** [comment]
I just pushed code (feedd7a392a371409b993bb056824ab81cc9fcb8) that will hopefully take care of this problem. If you find a way where this message is erroneously displayed, let me know :)

**Comment by whatSocks** [comment]
Still happening. 

<img width="908" alt="screenshot 2017-05-16 11 25 36" src="https://cloud.githubusercontent.com/assets/2731744/26114115/732ebcc2-3a2a-11e7-9621-48a862e53d23.png">

setup steps that might not be necessary

* add two methods to User + save so both show the stars
* close the edit menu
* open it
* delete a method

steps that are probably necessary

* add a method press the checkmark -> it will turn into a star
* press the star of the new method -> see error message

**Comment by whatSocks** [comment]
Also I don't know what pressing the star means/does, so some on hover text would be nice.

**Comment by vigorouscoding** [comment]
The message you see lets you know that the Schema has been recompiled into java code. That means that from that moment on your changes are available application-wide.
The star has a hover text (which pops up after ~2s for me) which says "Add to favourites". This is a feature where you can add files/methods/etc to favourites and edit them all in a convenient place (just press Ctrl-Alt-F to show/hide the favorites area).

I just made another - more significant - change to the notification feature. From the next snapshot on the sessionid, which triggered the schema recompile, is exempted from the list of clients who get a notification. The identification is session-based, so if you are logged into the same account in two separate browser-windows (i.e. one regular and one private window), you would get a notification in the window which has not triggered the change.

**Comment by whatSocks** [comment]
👍 works for meee
